spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/antips?serverTimezone=UTC
#    url: jdbc:mysql://mysql-container:3306/antips?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

    username: root
    password: 4245
  jpa:
    hibernate:
      ddl-auto: update  # 개발 환경에서는 update 또는 create-drop 사용
    properties:
      hibernate:
#        ddl-auto: create  # 개발 환경에서는 update 또는 create-drop 사용
        show_sql: true
        format_sql: true  # sql query formatting
        use_sql_comments: true  # sql 쿼리의 추가정보를 보여줍니다
  application:
    name: service-server
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

server:
  port: 8082

logging:
  level:
    org.springframework.batch: DEBUG
    org.springframework.jdbc: DEBUG
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

eureka:
  client:
    # 유레카 서버에 등록 true
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
 #      defaultZone: http://eureka-server:8761/eureka/
  instance:
    appname: SERVICE-SERVER
    instance-id: service-server:${spring.application.instance_id:${random.value}}